### ISSUE TITLE
Images disappear after installing CodePush update  .. with react-native-navigation .. docs 

### ISSUE THREAD

**Issue by coderjonny** [Microsoft/react-native-code-push#1235]
Hi, I'm debugging an issue with codepush and `react-native-navigation`.
The icons in the bottom navigation bar disappears after a codepush update.

In the [README](https://github.com/Microsoft/react-native-code-push#debugging--troubleshooting) it says:  

```
If your app is using the React Native assets system to load images (i.e. the require(./foo.png) syntax), then you MUST release your assets along with your JS bundle to CodePush. Follow these instructions to see how to do this.
```

What are those instructions?  Is this issue outdated? 
Do you have to explicitly release assets ? 

### Expected Behavior
Get more info when clicking on "these instructions"

### Actual Behavior
What actually happens?

<img width="889" alt="screen shot 2018-03-19 at 5 15 41 pm" src="https://user-images.githubusercontent.com/753091/37629567-b6b150c2-2b9c-11e8-8660-4d606a4c7b47.png">

What are those `instructions` in the README https://github.com/Microsoft/react-native-code-push#debugging--troubleshooting? 
Doesn't seem to link to anything.

### Environment

* react-native-code-push version: 
 "appcenter-cli": "^1.0.11"

* react-native version:
    "react-native": "^0.53.3"

* iOS/Android/Windows version:
ios.
* Does this reproduce on a debug build or release build?
release.
* Does this reproduce on a simulator, or only on a physical device?
physical device.

**Comment by markmadlangbayan** [comment]
Same here, how do you properly add assets on iOS and Android?

**Comment by iTOYS** [comment]
Hi guys,
You are right, the readme a bit outdated. 
You don't need to do something special to publish your assets if you use it [properly](https://facebook.github.io/react-native/docs/images.html#static-image-resources):
```
// GOOD
<Image source={require('./my-icon.png')} />;

// BAD
var icon = this.props.active ? 'my-icon-active' : 'my-icon-inactive';
<Image source={require('./' + icon + '.png')} />;

// GOOD
var icon = this.props.active
  ? require('./my-icon-active.png')
  : require('./my-icon-inactive.png');
<Image source={icon} />;
```

Thanks!

**Comment by pietro909** [comment]
@coderjonny @markmadlangbayan did anyone of you people solve the issue? We've just started experiencing it one week ago, on Android only (exactly the same codebase), whereas it used to work properly before.

@iTOYS we are following the practices that you reported here.

What else can be done?

**Comment by markmadlangbayan** [comment]
@pietro909 we're following @iTOYS ' recommendation.

**Comment by sijad** [comment]
we're facing same issue, with react-native-navigation, it was working alright before

**Comment by l1br3** [comment]
@pietro909 

I'm facing an issue which looks similar. My images get stretched, blurred, zoomed in a very non-consistent way. I use Animated.Image and it leads to very strange results.

I require all my images in a config file like this:
```js
export default {
  like: require('../Images/Icons/like.png'),
  dislike: require('../Images/Icons/dislike.png'),
  favorite: require('../Images/Icons/favorite.png'),
}
```

And then use them like this:
```js
<Animated.View style={[
      styles.heartBubbleHolder,
       {left: '55%'},
       {
         height: this.animatedValuesHeight[ 3 ],
        }
]}>
        <Animated.Image source={Images.like} style={{
            width: this.animatedValuesSizes[ 3 ],
            height: this.animatedValuesSizes[ 3 ],
            opacity: this.animatedValuesOpacities[ 3 ]
          }}/>
</Animated.View>
```

Any codepush update gonna break the images.
Before update:
![screenshot from 2018-12-17 19-53-38](https://user-images.githubusercontent.com/3482025/50108416-7a4e8800-0235-11e9-8c46-fd7a941d5dc1.png)

After update:
![screenshot from 2018-12-17 19-50-43](https://user-images.githubusercontent.com/3482025/50108348-44110880-0235-11e9-8b94-a42c3eb6c97d.png)

PS: I'm not releasing my JS assets along my bundle as instructions are not here anymore.

**Comment by pietro909** [comment]
hi @l1br3 the issue for us was solved in October after the latest RN update: we also upgraded all the other dependencies and apparently in our case was [FastImage](https://github.com/DylanVann/react-native-fast-image) the problem.

**Comment by l1br3** [comment]
Hi @pietro909 I actually run the latest RN@0.57.7 and I still face this issue.
I not use fastimage in my project

**Comment by l1br3** [comment]
Ho I thought you was working for the codepush team ! Sorry

**Comment by AshokICreate** [comment]
same issue here images are getting blurred after code push update.

**Comment by l1br3** [comment]
@AshokICreate what version of React Native are you using ?

**Comment by guruparan** [comment]
I'm using RN 58.5 with React Native Navigation 2, i'm facing the same issue, is there a fix for this ?

**Comment by MufeedaFi** [comment]
how do you properly add assets on iOS and Android? Even if the changes in bundle file is reflected with an update, why is all the images missing?
