### ISSUE TITLE
An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by SudoPlz** [Microsoft/react-native-code-push#1257]
I've been receiving:

```
java.lang.RuntimeException An error occurred while executing doInBackground() 
    AsyncTask.java:309 android.os.AsyncTask$3.done
    FutureTask.java:354 java.util.concurrent.FutureTask.finishCompletion
    FutureTask.java:223 java.util.concurrent.FutureTask.setException
    FutureTask.java:242 java.util.concurrent.FutureTask.run
    ThreadPoolExecutor.java:1113 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:588 java.util.concurrent.ThreadPoolExecutor$Worker.run
    Thread.java:818 java.lang.Thread.run


Caused by: com.microsoft.codepush.react.CodePushUnknownException Error closing IO resources. 
    FileUtils.java:176 com.microsoft.codepush.react.FileUtils.unzipFile
    CodePushUpdateManager.java:218 com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage
    CodePushNativeModule.java:210 com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground
    CodePushNativeModule.java:204 com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground
    AsyncTask.java:295 android.os.AsyncTask$2.call
    FutureTask.java:237 java.util.concurrent.FutureTask.run
    ThreadPoolExecutor.java:1113 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:588 java.util.concurrent.ThreadPoolExecutor$Worker.run
    Thread.java:818 java.lang.Thread.run


Caused by: java.util.zip.ZipException invalid stored block lengths 
    ZipInputStream.java:360 java.util.zip.ZipInputStream.read
    Streams.java:159 libcore.io.Streams.skipByReading
    InflaterInputStream.java:213 java.util.zip.InflaterInputStream.skip
    Streams.java:133 libcore.io.Streams.skipAll
    ZipInputStream.java:144 java.util.zip.ZipInputStream.closeEntry
    ZipInputStream.java:115 java.util.zip.ZipInputStream.close
    FileUtils.java:172 com.microsoft.codepush.react.FileUtils.unzipFile
    CodePushUpdateManager.java:218 com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage
    CodePushNativeModule.java:210 com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground
    CodePushNativeModule.java:204 com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground
    AsyncTask.java:295 android.os.AsyncTask$2.call
    FutureTask.java:237 java.util.concurrent.FutureTask.run
    ThreadPoolExecutor.java:1113 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:588 java.util.concurrent.ThreadPoolExecutor$Worker.run
    Thread.java:818 java.lang.Thread.run
```

in production Android devices > version 6.

Could that be a duplicate of https://github.com/Microsoft/react-native-code-push/issues/873 ?

**Comment by iTOYS** [comment]
Hi @SudoPlz 
Yes it can. Have you tried fix your issue as mentioned in #873 ?

**Comment by SudoPlz** [comment]
I'm going to try and post back.

Here's my code:

 @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        // We need this in order to fix https://github.com/Microsoft/react-native-code-push/issues/1257#issuecomment-381944498
        CodePush.getJSBundleFile(); // we must run this before setLayout takes place
        // a.k.a before super.onCreate

        super.onCreate(savedInstanceState);
    }

Unfortunately since I'm using `react-native-navigation` I don't have fine control over when `setContentView` get's called, do you think that will be ok @iTOYS ?

**Comment by SudoPlz** [comment]
ok, so I can't do that because I receive:

```
       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.testapp.app.android/com.testapp.app.android.MainActivity}: com.microsoft.codepush.react.CodePushNotInitializedException: A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?
              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
              at android.app.ActivityThread.-wrap12(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
              at android.os.Handler.dispatchMessage(Handler.java:102)
              at android.os.Looper.loop(Looper.java:154)
              at android.app.ActivityThread.main(ActivityThread.java:6119)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
           Caused by: com.microsoft.codepush.react.CodePushNotInitializedException: A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?
              at com.microsoft.codepush.react.CodePush.getJSBundleFile(CodePush.java:186)
              at com.microsoft.codepush.react.CodePush.getJSBundleFile(CodePush.java:181)
              at com.testapp.app.android.MainActivity.onCreate(MainActivity.java:25)
              at android.app.Activity.performCreate(Activity.java:6679)
              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
              at android.app.ActivityThread.-wrap12(ActivityThread.java) 
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
              at android.os.Handler.dispatchMessage(Handler.java:102) 
              at android.os.Looper.loop(Looper.java:154) 
              at android.app.ActivityThread.main(ActivityThread.java:6119) 
              at java.lang.reflect.Method.invoke(Native Method) 
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

:/

Is there any other place I can run `getJSBundleFile` ?

**Comment by SudoPlz** [comment]
Ok so back to ground zero. No idea what to tryt.

**Comment by manjeetwadi** [comment]
@SudoPlz any success resolving this issue, I am facing same in app with react-native-navigation

**Comment by SudoPlz** [comment]
Nope, no success yet @manjeetwadi

**Comment by anuraginwadi** [comment]
Facing the same issue. +1

**Comment by alexandergoncharov** [comment]
Hi all,

We are working on it.

**Comment by SudoPlz** [comment]
Awesome, thanks for the update @alexandergoncharov we'll be patiently standing by.

:)

**Comment by shashankwadi** [comment]
+1

**Comment by alexandergoncharov** [comment]
Hi @SudoPlz, @manjeetwadi, @anuraginwadi, @shashankwadi,,

Could you please provide some part of your code which can help me to reproduce this issue?

Thanks,
Alexander

**Comment by SudoPlz** [comment]
Unfortunately I was not able to reproduce that at will. We only received that on our crash-reporter (bugsnag).

Maybe someone else knows more?

**Comment by manjeetwadi** [comment]
similar thing happened for us too

**Comment by half-ogre** [comment]
Howdy folks, just a quick update that we're are still looking at this. We are trying to reproduce it and make sure we understand it and weighting the pros and cons of possible solutions. My hope is we have something sorted next week, but I can't make any promises. I am new to the project and have some catching up to do, so I apologize that this also is making things a little slower.

**Comment by half-ogre** [comment]
I generally favor the first approach. @max-mironov and @sergey-akhalkov, do you have any thoughts on this?

**Comment by NickToropov** [comment]
Hi @half-ogre,
we discussed the issue with @max.mironov and @sergey.akhalkov and our thought is also that plugin shouldn’t crash the app, but we suggest just to add catching and logging of CodePushUnknownException. 
There is no point to implementing something more complex here as brownfield-apps-dev branch already contains similar mechanism https://github.com/Microsoft/react-native-code-push/blob/brownfield-apps-dev/android/app/src/main/java/com/microsoft/codepush/common/utils/CodePushLogUtils.java#L57

**Comment by half-ogre** [comment]
Even better. Let's move forward with that. Thanks!

**Comment by alexandergoncharov** [comment]
Hi all,

I made PR for preventing crashes of app by catching Exceptions. Could please someone test it?
https://github.com/Microsoft/react-native-code-push/pull/1286

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi all,
Changes are published in 5.3.4 version: https://github.com/Microsoft/react-native-code-push/releases/tag/v5.3.4

I'll close this issue as it was resolved by hot fix but please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by SudoPlz** [comment]
Thanks @alexandergoncharov

**Comment by dooleyb1** [comment]
Still experiencing this issue on an app running `react-native-code-push@7.0.0`. This is the first time it has appeared in our Crashlytics after using code push for quite some time. Currently only affecting a single user which is quite strange.

```
Caused by java.lang.NullPointerException
       at java.io.File.<init>(File.java:283)
       at com.microsoft.codepush.react.FileUtils.copyDirectoryContents(FileUtils.java:19)
       at com.microsoft.codepush.react.CodePushUpdateUtils.copyNecessaryFilesFromCurrentPackage(CodePushUpdateUtils.java:100)
       at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:242)
       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:290)
       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by Gitarcitano** [comment]
I'm facing the same with v7.0.1
