### ISSUE TITLE
(linker command failed with exit code 1) when Archiving for IOS

### ISSUE THREAD

**Issue by bgold0** [Microsoft/react-native-code-push#1433]
Getting an error when I try to Archive my project for distribution.

### Steps to Reproduce
1. New react-native init
2. `npm install appcenter appcenter-analytics appcenter-crashes --save`
3. `react-native link`
4. `npm install --save react-native-code-push`
5. `react-native link react-native-code-push`

Simulator works fine. But then Archiving gives an error.

### Expected Behavior
I expect the archive to work.

### Actual Behavior
Fails to archive:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CodePush", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Environment

* react-native-code-push version: ^5.4.2
* react-native version: ^0.57.1
* iOS/Android/Windows version: XCODE 9.4 (9F1027a)
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Does not reproduce on simulator, but does reproduce when trying to Archive the project

**Comment by bgold0** [comment]
I did a manual installation without Pods and it seems to work. There is some linking issues in there but I don't want to mess with it anymore in fear that I might mess it up again.

**Comment by alexandergoncharov** [comment]
Yeah, `appcenter` package using pods and that is reason of issue. Manual installation also helps.
We'll investigate this issue for `link` command. 

As issue was resolved I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by keung7252** [comment]
still not working after Manual installation

**Comment by yamov** [comment]
@alexandergoncharov I still have problems with linking via pods. I can successfully build the app when code push is linked manually, but it still fails with the same error when linked via pods.
Is there any solution to do it via pods?
