### ISSUE TITLE
[Bug] Xcode 11 support

### ISSUE THREAD

**Issue by kesha-antonov** [microsoft/react-native-code-push#1665]
Hey!

I'm unable to use code-push with Xcode 11.
Becasuse Info.plist contains
```
<key>CFBundleShortVersionString</key>
<string>$(MARKETING_VERSION)</string>
```
And I receive error
```
Detecting ios app version:

Error: Command 'codepush release-react -a name/app_name -d Staging' failed with exception "The "CFBundleShortVersionString" key in the "ios/app_name/Info.plist" file needs to specify a valid semver string, containing both a major and minor version (e.g. 1.3.2, 1.1)."

```

### Steps to Reproduce
1. Open Xcode 11
2. Set app version
3. Try code push

### Expected Behavior
Build & upload

### Actual Behavior
Fails

### Environment

* react-native-code-push version: 5.7.0
* react-native version: 0.59.10
* iOS/Android/Windows version: iOS 13.0
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by solidfox** [comment]
You can work around it by manually adding `-t [your target version]` to the end of the react-release command.

**Comment by felixchan** [comment]
+1

**Comment by Alaa-Ben** [comment]
Any news on this ?

**Comment by tdinckaya** [comment]
> You can work around it by manually adding `-t [your target version]` to the end of the react-release command.

thanks.

**Comment by kadirakkaya** [comment]
Change the $(MARKETING_VERSION) to your version number after build in Xcode.
I tried today and it works for me. 
I uploaded my version to App Store. I download my app from "Test Flight" app. And I use code-push release with new version number and  without using -t option.

**Comment by SurajMDurgad** [comment]
If anybody is struggling with `-t` command, the build number from the xcode should be passed in double quotes - `-t "4.6.2"` something like this.

**Comment by elribonazo** [comment]
pfff....

**Comment by AndrewMorsillo** [comment]
@kadirakkaya 's solution works great. Edit your version number in Xcode, then just do a search for `MARKETING_VERSION` and replace it with your version number. Annoying extra step when making a new build version but easy enough and it works around the issue.

**Comment by andreidubov** [comment]
Hi @kesha-antonov ,
Thank you for reporting!

I hope @kadirakkaya and @AndrewMorsillo answers were helped you, so I'll close the issue for now, but if you still have any questions, feel free to reopen it.

**Comment by kesha-antonov** [comment]
Thanks guys!

**Comment by sunweiyang** [comment]
@andreidubov Will full Xcode 11 support (i.e. support for `$(MARKETING_VERSION)`) be provided in a future release? The latest release (react-native-code-push@6.1.0) still requires this workaround; it'd be a cleaner developer experience if we didn't need to have this extra step.

**Comment by andreidubov** [comment]
Hi @sunweiyang, We know about this problem and plan to fix it soon. I will keep you updated.
Thank you for your question.

**Comment by jesobreira** [comment]
What we've done is to put the release-react command as a npm script and instead of hardwritting the -t [version], used [jq](https://stedolan.github.io/jq/) to pick it from package.json:

```json
scripts: {
  "codepush": "appcenter codepush release-react ... -t `cat package.json | jq .version`"
}

**Comment by andreidubov** [comment]
Hi guys, 
We released a fix for Xcode 11. Now it should work well.
If you have any suggestions or comments, you can add it here or open a new issue.

PR link: https://github.com/microsoft/appcenter-cli/pull/751

**Comment by dihan** [comment]
I'm still having this issue on "react-native-code-push": "6.2.0"
Was thee fix merged with this version?

**Comment by CyberMew** [comment]
Still broken on 6.3.0 for me. Have to supply -t manually for it to work. I am using xcconfig (set via pod install) to set the MARKETING_VERSION if that affects anything.

**Comment by vkachan** [comment]
@dihan @CyberMew this has nothing to do with react-native-code-push as fix was done for appcenter-cli. I had to remove appcenter-cli entirely and reinstall it again. Please check if you have it installed globally with -g flag as it said in the appcenter-cli manual.

**Comment by CyberMew** [comment]
> @dihan @CyberMew this has nothing to do with react-native-code-push as fix was done for appcenter-cli. I had to remove appcenter-cli entirely and reinstall it again. Please check if you have it installed globally with -g flag as it said in the appcenter-cli manual.

app center or code push is already the latest and global for me. In fact I just installed it for the first time a couple days ago, which by the time this issue is supposedly fixed.

**Comment by MobileMon-Majestic** [comment]
I'm still getting this error

**Comment by phanvungoc96** [comment]
``still this error with RN 0.76
with command "appcenter codepush release-react -a <appHolder>/<appName> -s Staging".

it can't auto get the marketing_version from project.pbxproj.  I have to add -t <app version> to command

`Error: Command 'codepush release-react -a name/app_name -d Staging' failed with exception "The "CFBundleShortVersionString" key in the "ios/app_name/Info.plist" file needs to specify a valid semver string, containing both a major and minor version (e.g. 1.3.2, 1.1)."
`

**Comment by AnatolyPristensky** [comment]
Hello @phanvungoc96 could you please share a content of your ios/app_name/Info.plist?
In particular - what value you have in `CFBundleShortVersionString` key?
