### ISSUE TITLE
 Error: The asset cannot be uploaded. Try creating a new one

### ISSUE THREAD

**Issue by daizhenhong** [microsoft/react-native-code-push#1680]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.I had create a app in appcenter,and create codepush version for android.
2. I use `appcenter codepush release-react -a shuziyixin/ywxAndroid` create a update.It's OK!
3.I change a file,then use `appcenter codepush release-react -a shuziyixin/ywxAndroid -m --description "2.second commit" -d Staging`,but it wrong!

### Actual Behavior
This is the wrong message?
```
bogon:yiwangxin-3.4.0 bjcaywq$ appcenter codepush release-react -a shuziyixin/ywxAndroid -m --description "2.second commit" -d Staging

Detecting android app version:

Using the target binary version value "3.4.0" from "android/app/build.gradle".

Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/v9/p66zw6ln5dn75v6rgq6cmgrr0000gn/T/code-push2019810-18818-ky2s06.4y44d/CodePush --bundle-output /var/folders/v9/p66zw6ln5dn75v6rgq6cmgrr0000gn/T/code-push2019810-18818-ky2s06.4y44d/CodePush/index.android.bundle --dev false --entry-file index.js --platform android
Loading dependency graph, done.

bundle: Writing bundle output to: /var/folders/v9/p66zw6ln5dn75v6rgq6cmgrr0000gn/T/code-push2019810-18818-ky2s06.4y44d/CodePush/index.android.bundle
bundle: Done writing bundle output
bundle: Copying 421 asset files
bundle: Done copying assets

Releasing update contents to CodePush:

Error: Error: The asset cannot be uploaded. Try creating a new one

```
### Environment

* react-native-code-push version:5.5.1
* react-native version:0.57.1
* iOS/Android/Windows version: android/9.0

**Comment by swbradsh** [comment]
I received this same error. In my case, I received this when I was connected behind a proxy server. I had http_proxy and https_proxy environment variables set. Commands like `appcenter apps list` worked fine, but doing a release produced this same error when it was trying to upload bundle to the cloud.  Once I connected to a regular network without a proxy, I was able to do a release just fine.

**Comment by mayurssoni2456** [comment]
Hi, I tried on home network, unfortunately, I am still getting the same error.

Also, created fresh new build - code push worked for only for the first time. 

**Error: Error: The asset cannot be uploaded. Try creating a new one
<img width="831" alt="Screen Shot 2019-10-03 at 7 42 21 PM" src="https://user-images.githubusercontent.com/8012078/66135283-4fdc8880-e617-11e9-80bf-40a5c003d599.png">
**

**Comment by gregoryBernard** [comment]
> I received this same error. In my case, I received this when I was connected behind a proxy server. I had http_proxy and https_proxy environment variables set. Commands like `appcenter apps list` worked fine, but doing a release produced this same error when it was trying to upload bundle to the cloud. Once I connected to a regular network without a proxy, I was able to do a release just fine.

Same issue.I have also http_proxy and https_proxy environment variables set. @swbradsh did you find a solution?

**Comment by swbradsh** [comment]
@gregoryBernard  Yes, I figured out a solution. Microsoft says it is not supported at this time, but I posted a work-around over here: https://github.com/microsoft/appcenter-cli/issues/682#issuecomment-572103918

**Comment by gregoryBernard** [comment]
Thx; didn't know appcenter wasn't supporting proxy. Solution is ugly but I really need it to work behind a proxy. Thanks

**Comment by alexandergoncharov** [comment]
Hi all,
I see that issue was resolved by tis comment: https://github.com/microsoft/react-native-code-push/issues/1680#issuecomment-572104323

I'm going to close this issue for now. Please feel free to reope it if you have any questions.

**Comment by MuhammadUsman786786** [comment]
I was facing the same issue on `mac Catalina`

**i had follow these docs**
https://docs.microsoft.com/en-us/appcenter/distribution/codepush/

I was facing an issue in `appcenter --version 2.9.0`

**Fix**
what I did is downgrade the `apocenter CLI version to  2.5.4` by running the command

`npm install -g appcenter-cli@2.5.4`

**Comment by swapnilgaikwad1507** [comment]
Is anyone still facing this issue?
I have installed code push and getting this issue for Android.
RN version : 0.67.1
appcenter cli version : 2.10.10
react-native-code-push: ^7.0.4

Note : I am behind proxy. Is it causing the issue or it should work with proxy too?
