### ISSUE TITLE
Error: The asset cannot be uploaded. Try creating a new one 

### ISSUE THREAD

**Issue by nchase** [microsoft/react-native-code-push#1965]
Bundle upload fails multiple times after bundling, but succeeds eventually. This time, it took me 4 tries. 

This seems to be a recent issue (we have done many dozens of CodePush updates without this issue. It probably started ~2-3 weeks ago).

Errors have this message: 

```
Error: The asset cannot be uploaded. Try creating a new one 
```

### Steps to Reproduce
1. See description above. Based on earlier issues, seems like this might be an error on the App Center servers. I have seen this happen multiple times in a few weeks. I wonder if it's worth clarifying the error message in these cases (assuming the App Center servers are returning information that provides enough information to do so)

### Expected Behavior
The bundle should be uploaded successfully

### Actual Behavior
What actually happens?
```
Error: The asset cannot be uploaded. Try creating a new one 
```

### Environment

* react-native-code-push version: ^6.2.0
* react-native version: 0.62.2
* iOS/Android/Windows version: N/A
* Does this reproduce on a debug build or release build? N/A
* Does this reproduce on a simulator, or only on a physical device? N/A

**Comment by nchase** [comment]
Looks like this might be related to the CodePush issue posted to https://status.appcenter.ms/ two weeks ago.

There's no messaging about that issue anywhere other than that page. This was very confusing until I discovered that page a few minutes ago.

**Comment by ruslan-bikkinin** [comment]
Hi @nchase and thanks for reporting. Yes, currently we experiencing issues with legacy CodePush API requests. Could you please clarify what cli and what version of it do you use to upload the bundle: legacy `code-push` cli or `appcenter-cli`?

**Comment by nchase** [comment]
Hi @ruslan-bikkinin – this is  `"appcenter-cli": "2.5.3"`

**Comment by ruslan-bikkinin** [comment]
@nchase could you please then add `--debug` parameter to the end of `appcenter codepush release-react <etc>` command, copy the output, remove sensitive information from logs like `x-api-token` value etc and share it with us? Make this only for the case when upload fails.
Also, please let us know what is your location (country).

**Comment by nchase** [comment]
Location: USA

I can run in debug mode the next time this fails – I actually tried to get this output last time I noticed a failure, but it succeeded when I ran in debug mode, of course 😄

**Comment by ruslan-bikkinin** [comment]
@nchase okay, got it. As command logs contains `X-Api-Token` header, application information like its name, organization etc I'd suggest you to open ticket on Intercom where we could discuss your case in private.
I'm closing the issue for now.

**Comment by MuhammadUsman786786** [comment]
I am facing the same issue again

`appcenter version 2.9.0`

i am running this command
`appcenter codepush release-react -a srs_ios -d Production --debug`
when I upload the bundle first time it works, but when I upload the bundle next time it does not work

**Comment by Farhankhaliid** [comment]
I fixed this issue by bundle the assets manually first with this command 
`react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
`
after that i run   `appcenter codepush release-react -a <ownerName>/MyApp-iOS -d Production --debug`

**Comment by leotm** [comment]
I weirdly got this too for the first time, tried again and it worked

**Comment by swapnilgaikwad1507** [comment]
Is anyone still facing this issue? 
I have installed code push and getting this issue for Android.
RN version : 0.67.1
appcenter cli version : 2.10.10
react-native-code-push: ^7.0.4

Note : I am behind proxy. Is it causing the issue or it should work with proxy too?

**Comment by Gautham495** [comment]
I used my iphone's hotspot - It was not uploading and caused this error.
I used my home wifi - It uploaded.

**Comment by aurangs7** [comment]
Same here @Gautham495 I was also using my iPhone's hotspot, which gave the same error. It's working with broadband wifi.

**Comment by tkud04** [comment]
> I fixed this issue by bundle the assets manually first with this command `react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios ` after that i run `appcenter codepush release-react -a <ownerName>/MyApp-iOS -d Production --debug` And its worked for me -:)

This worked for me, but in my case I used the appcenter codepush release command instead, after generating the bundle
