### ISSUE TITLE
[Android Only]  Error! Public key was provided but there is no JWT signature within app bundle to verify.

### ISSUE THREAD

**Issue by tronginc** [microsoft/react-native-code-push#2141]
It works on IOS! Same private.pem & public.pem.

### Expected Behavior
What you expected to happen?

### Actual Behavior
After download and extract the bundle's content:
![image](https://user-images.githubusercontent.com/33952884/132532276-b03c90f5-ddb0-490f-b4f0-40115ac68667.png)

I got this error: 

```
Public key was provided but there is no JWT signature within app bundle to verify. Possible reasons, why that might happen:
1. You've been released CodePush bundle update using version of CodePush CLI that is not support code signing.
2. You've been released CodePush bundle update without providing --privateKeyPath option.
```

### Step
- Key generation
```
# generate private RSA key and write it to private.pem file
openssl genrsa -out private.pem

# export public key from private.pem into public.pem
openssl rsa -pubout -in private.pem -out public.pem
```

- Add CodePushPublicKey string item to `android/app/src/main/res/values/strings.xml`

- Double check https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android

- Release command:
```shell
appcenter codepush release-react \
     -a MyCompany/MyApp \
     -d Staging \
     -k private.pem \
     -m --description "Release a test update"
```

### Environment

* react-native-code-push version: 7.0.2
* react-native version: 0.64.1
* iOS/Android/Windows version: Android 11, Windows 10
* Does this reproduce on a debug build or release build? Debug and Release
* Does this reproduce on a simulator, or only on a physical device? All

**Comment by immutable-pro** [comment]
I have started observing exactly the same issue, Android Only, just today.

**Comment by vishal-android-freak** [comment]
Facing the same isssue

**Comment by immutable-pro** [comment]
The exception is:

```
[CodePush] Exception
com.microsoft.codepush.react.CodePushInvalidUpdateException: Error! Public key was provided but there is no JWT signature within app bundle to verify. Possible reasons, why that might happen: 
1. You've been released CodePush bundle update using version of CodePush CLI that is not support code signing.
2. You've been released CodePush bundle update without providing --privateKeyPath option.
	at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:279)
	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:290)
	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

The generated signature path is:

```
signaturePath /data/user/0/[app]/files/CodePush/116f592802ca60efc8aae3bcad609d793b33145c48e99ebfe8bcbf4b1f9630b6/CodePush/.codepushrelease
```

**Comment by immutable-pro** [comment]
This change is very suspicious...
https://github.com/microsoft/react-native-code-push/compare/v7.0.1...v7.0.2

**Comment by immutable-pro** [comment]
I can confirm that locking `react-native-code-push"` to `"7.0.1"` fixes the issue.

**Comment by wijskinner** [comment]
This is actually extra annoying as as far as I can see the fix itself can't be code-pushed. 🙃

**Comment by regalstreak** [comment]
Confirmed. 7.0.2 is a non working release for Android. Downgraded to 7.0.1 and it worked like it used to

**Comment by immutable-pro** [comment]
I don't know if it is related or not, but right now, I can't release. The only information I get back is:

```
Error: Failed to release a CodePush update.
```

Using appcenter-cli version 2.10.0

**Comment by felipeaugusto1** [comment]
I'm using 7.0.1 with React Native 0.65.1 and it's not working

**Comment by immutable-pro** [comment]
Hi @felipeaugusto1. According to the documentation at https://github.com/microsoft/react-native-code-push#supported-react-native-platforms 0.65.x requires 7.2+. So I am afraid you will have to wait until this bug gets fixed, if you can't downgrade your RN version.

**Comment by felipeaugusto1** [comment]
I didn't notice that @immutable-pro . Thank you for the info

**Comment by felipeaugusto1** [comment]
I was able to get the 7.0.3 version working with react-native 0.65.1. Just had to downgrade `com.android.tools.build:gradle` to 4.0.1

**Comment by gabrielmoncea** [comment]
Neither 7.0.2 or 7.0.3 solves this issue.

**Comment by wemmarcovecchio** [comment]
I have the same issue. I downgrading Code push version from 7.0.3 to 7.0.1, Neither 7.0.2 or 7.0.3 solves this issue.

**Environment**
react-native-code-push version: 7.0.1
react-native version: 0.65.1
Android version: Android 11
Does this reproduce on a debug build or release build? Debug and Release
Does this reproduce on a simulator, or only on a physical device? All

**Comment by wemmarcovecchio** [comment]
> Confirmed. 7.0.2 is a non working release for Android. Downgraded to 7.0.1 and it worked like it used to

Which version of react-native are you using?

**Comment by gabrielmoncea** [comment]
I've tested it on 0.64.2

**Comment by chirag-jain-furlenco** [comment]
I am facing the same issue
When I build release apk from my system (v7.0.4), app is getting updated via codepush
But release apk from my colleague's system, are not getting updated. Instead, its failing after downloading step

**Comment by snkhan120** [comment]
Problem has been solved!

Follow the steps:
1- In package.json change version of "react-native-code-push"  "^7.0.1" to "^7.0.4",
2- Delete node_modules folder
3- npm install or yarn install
4- npm install --package-lock-only

[CodePush] Reporting binary update (2.2.1)
 LOG  [CodePush] Awaiting user action.
 LOG  [CodePush] Downloading package.
 LOG  [CodePush] Installing update.

**Comment by casaumayman** [comment]
![Screen Shot 2022-02-23 at 16 24 16](https://user-images.githubusercontent.com/42993140/155291818-791df90d-8d82-48cd-b4ca-18a400235aaa.png)
I still get this issue. Any update?

**Comment by patelbansari** [comment]
I'm still facing this issue on Android. Any update?
```
"react-native": "0.70.3",
"react-native-code-push": "^7.0.5",
```

i added my `CodePushPublicKey` in `strings.xml`.
also i'm using below one to update the release in appcenter.

`appcenter codepush release-react -a <ownerName>/<appName> -t 20.27.7 -d Staging -k private.pem
`
