### ISSUE TITLE
Changes not effecting android app,After successful uploading through code push

### ISSUE THREAD

**Issue by shihabudheenc** [microsoft/react-native-code-push#2401]
I followed the official documentation of the code push from Microsoft. After the successful implementation and code uploading, the changes are not reflected on the android app. After I install the application on my device, the changes do not reflect in the App center.
Can anybody suggest any solutions? Thank you

**Comment by nhanders** [comment]
One issue that a few users have reported and I've experienced is the changes are failing to install after download, and thus the bundle is being rolled back. If it is this case, it seems like it is being fixed in the next release.

If you look on the CodePush console, check whether it Rollbacks is non-zero on Android for the given deployment.

**Comment by malikzype** [comment]
The fix rolled out in CodePush 7.1.0 isn't working for us. We are still getting issues with RollBack.
