### ISSUE TITLE
Android app revert to first bundle after code-push update, instead of downloaded one

### ISSUE THREAD

**Issue by sulliwane** [Microsoft/react-native-code-push#98]
I added code-push to my Android react-native app:

![screenshot from 2015-12-08 23 24 51](https://cloud.githubusercontent.com/assets/1733686/11659405/150a73ee-9e03-11e5-858a-d394ac3df09f.png)

and then installed **1.0.0** on my phone. Then updated the JS to **1.0.1**, bundled and pushed to Code-push. Start the app on the phone, with debug on and I see:

![screenshot from 2015-12-08 23 27 37](https://cloud.githubusercontent.com/assets/1733686/11659455/4ad7bdd8-9e03-11e5-8e6c-fcd1fe5a2f77.png)

So I kill the app and start again, and now my app version is still **1.0.0**.

So I download the **1.0.1** from the app dev mode by setting the ip server of my computer (debug server host). And then update the JS to **1.0.2**, bundle and push to code-push:

![screenshot from 2015-12-08 23 24 12](https://cloud.githubusercontent.com/assets/1733686/11659536/bca0cc02-9e03-11e5-811a-d4c071aa8bb5.png)

I relaunch my app, I can see in chrome debugger that it's downloading the bundle from code-push. Once finished, I remove my computer ip from the app dev menu (debug server host), and restart the app.

And I can see that it's back to **1.0.0** in my app settings page.

I manually downloaded the main.jsbundle from code-push server (both) and checked their content, they are indeed marked as **1.0.1** and **1.0.2**.

So it looks like the android app is not loading the freshly downloaded jsbundle, but instead the one from the react-native run-android install.

Now I see:

![screenshot from 2015-12-08 23 39 34](https://cloud.githubusercontent.com/assets/1733686/11659861/594c20be-9e05-11e5-84a9-16b627836c13.png)

but code-push jsbundle is **1.0.2** and my app display the **1.0.0** jsbundle.

Any ideas?

many thanks.

**Comment by lostintangent** [comment]
When you put React Native into debug mode, it will always pull the bundle from the packager server, so even though you're specifying that the JS bundle should come from CodePush, the line that enables dev support will actually trump it. So it seems like the update is being discovered and installed, but when the app actually restarts, it pulling the app version from the packager. 

If you try running the app in release mode, do you see the updates after restart? The code you linked above disables dev support in release mode which is why I asked.

**Comment by sulliwane** [comment]
Will try tomorrow! Thx

On 9 December 2015 00:32:06 GMT+08:00, Jonathan Carter <notifications@github.com> wrote:
>When you put React Native into debug mode, it will always pull the
>bundle from the packager server, so even though you're specifying that
>the JS bundle should come from CodePush, the line that enables dev
>support will actually trump it. So it seems like the update is being
>discovered and installed, but when the app actually restarts, it
>pulling the app version from the packager. 
>
>If you try running the app in release mode, do you see the updates
>after restart? The code you linked above disables dev support in
>release mode which is why I asked.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Microsoft/react-native-code-push/issues/98#issuecomment-162937343

-- 
Sent from my phone with K-9 mail.

**Comment by sulliwane** [comment]
I just tried with IOS in the simulator (release: production, so no DEV menu), the update dialog show up, then it downloads (looking at the apple networking tool), after 5min with no network activity, I kill the app in the simulator, restart it. And no difference, the version is not the one downloaded from internet. However, no update dialog show up this time, which means that code-push believes that the current in-use jsbundle is up to date (but it is clearly not the most recent).

I will try with android later, but the problem seems to be the same. I'm wondering how to debug that.

**Comment by lostintangent** [comment]
Are you using the new assets support by any chance? We just fixed a bug where the plugin wasn't giving priority to an update if it was uploaded to CodePush earlier than the running binary was built. If you are using assets, you could test whether this is your problem by running the app from Xcode, then releasing an update to CodePush, restart the app and install the update. Restart the app again and if you see your update, then you're hitting the bug we just fixed.

**Comment by sulliwane** [comment]
Yes, I'm using **the new assets support**.

I restarted a few times, and the app is still showing the old jsbundle. Moreover, I'm always building first, then make a modification in my JS, then:

 ```react-native bundle --platform ios --entry-file index.ios.js --bundle-output ./release/main.jsbundle --assets-dest ./release``` 

then:

 ```code-push release appName ./release 1.0.0 --deploymentName Production_ios --description 'code push 1.4.1 for ios with assets V1.0.6'```

So I'm not quite sure this bug apply in my case. Maybe I should revert to jsbundle only.

**Comment by lostintangent** [comment]
Would you be willing to try running "npm install Microsoft/react-native-code-push" and trying this scenario to see if the bug fix we submitted fixes your issue. I just tested this again and can't repro your issue.

BTW, just to also double check, are you setting the JS bundle location in your AppDelegate file to the CodePush bundleURL? I'm sure this is a stupid question but I just wanted to double check :)

**Comment by sulliwane** [comment]
AppDelegate was correctly set :) I just ```npm install Microsoft/react-native-code-push```, and it WORKS! Thanks. Finally code-push is applying the update. Awesome. I trying with android now (I'm wondering, for Android, I can bundle and push with assets, but code-push for android will just apply the jsbundle and ignore the assets right?)

**Comment by lostintangent** [comment]
Yay!!!! Thank you so much for trying that. I'll release a patch update to NPM tomorrow with this fix and a few others.

On Android, you need to release just the bundle. The Android client doesn't currently support being given a directory so it would behave unexpectedly. We've got a PR out to React Native to add support to the platform for dynamically updating assets on Android. Once that is merged in and released to NPM, we'll update our plugin to support it.

**Comment by lostintangent** [comment]
Hey @sulliwane, I went ahead and released a patch update to NPM, so you can go ahead and switch back to an NPM-based dependency if you'd like. The 1.4.2 release includes the fix for your issue, as well as better error logging.

**Comment by sulliwane** [comment]
perfect, using 1.4.2 right now. Working fine on IOS. :+1:  

on Android (bundled with JS only) it's working only if I "reload JS" from dev menu (packager not running on my computer, so it's not fetching the JSbundle from my computer for sure). But if, after code-push download the new jsbundle in the phone, I kill the app and start again, it won't use the newly downloaded jsbundle. I have to "reload JS" from dev menu.

Note: I didn't try with Android APP that has not the dev menu enabled. Will try later (not sure yet how to use assembleRelease)

**Comment by geof90** [comment]
@sulliwane, does it work if you comment out `.setUseDeveloperSupport(BuildConfig.DEBUG)`?

**Comment by MrPluto** [comment]
:+1:

**Comment by sulliwane** [comment]
@geof90 Awesome, Disabling DEV mode works on Android. Looking forward your workaround, as well as Android assets support :) Thanks a lot.

(note: "reload JS" was actually loading from the computer, I just didn't notice it, my bad).

**Comment by sulliwane** [comment]
@lostintangent Could you please confirm that the only parameter that will fire a code-push download is the hash of the bundle (different with local = download, same with local = up to date) ? Thanks.

**Comment by lostintangent** [comment]
It's a combination of the hash and the version of the running binary. So if you're running v1.0.0, with hash "6789", and the latest update on your deployment is a different hash, but associated with v1.0.1, then the client wouldn't get the update.

**Comment by sulliwane** [comment]
Got it. I forgot about the version of the binary. thanks.
